CREATE TABLE `data_platform_inspection_lot_confirmation_header_data`
(
		`InspectionLot`                              int(16) NOT NULL,
        `Operations`                                 int(16) NOT NULL,
        `OperationsItem`                             int(6) NOT NULL,
        `OperationID`                                int(4) NOT NULL,
        `ConfirmationCountingID`                     int(4) NOT NULL,
        `Inspection`                                 int(6) NOT NULL,
		`ProductionOrder`                            int(16) NOT NULL,
    	`ProductionOrderItem`                        int(6) NOT NULL,
        `InspectionType`                             varchar(100) NOT NULL,
        `InspectionTypeValueUnit`                    varchar(3) DEFAULT NULL,
        `InspectionTypePlannedValue`                 float(15) DEFAULT NULL,
        `InspectionTypeCertificateType`	             varchar(20) DEFAULT NULL,
        `InspectionTypeCertificateValueInText`       varchar(20) DEFAULT NULL,
        `InspectionTypeCertificateValueInQuantity`   float(15) DEFAULT NULL,
        `InspectionLotInspectionText`	             varchar(200) DEFAULT NULL,
        `InspectionTypeConfirmedValueInText`         varchar(20) DEFAULT NULL,
        `InspectionTypeConfirmedValueInQuantity`     float(15) DEFAULT NULL,
        `InspectionResult`                           tinyint(1) DEFAULT NULL,
        `OperationPlannedQuantityInBaseUnit`         float(15) NOT NULL,
        `OperationPlannedQuantityInProductionUnit`   float(15) NOT NULL,
        `OperationPlannedQuantityInOperationUnit`    float(15) NOT NULL,
        `ProductBaseUnit`                          	 varchar(3) NOT NULL,
		`ProductProductionUnit`						 varchar(3) NOT NULL,
        `ProductOperationUnit`                       varchar(3) NOT NULL,
        `OperationPlannedScrapInPercent`             float(7) DEFAULT NULL,
        `ConfirmationEntryDate`                      date DEFAULT NULL,
        `ConfirmationEntryTime`                      time DEFAULT NULL,
        `ConfirmationText`                           varchar(200) DEFAULT NULL,
        `IsFinalConfirmation`                        tinyint(1) DEFAULT NULL,
        `WorkCenter`                                 int(16) NOT NULL,
        `EmployeeIDWhoConfirmed`                     int(20) NOT NULL,
        `ConfirmedExecutionStartDate`                date DEFAULT NULL,
        `ConfirmedExecutionStartTime`                time DEFAULT NULL,
        `ConfirmedSetupStartDate`                    date DEFAULT NULL,
        `ConfirmedSetupStartTime`                    time DEFAULT NULL,
        `ConfirmedProcessingStartDate`               date DEFAULT NULL,
        `ConfirmedProcessingStartTime`               time DEFAULT NULL,
        `ConfirmedExecutionEndDate`                  date DEFAULT NULL,
        `ConfirmedExecutionEndTime`                  time DEFAULT NULL,
        `ConfirmedSetupEndDate`                      date DEFAULT NULL,
        `ConfirmedSetupEndTime`                      time DEFAULT NULL,
        `ConfirmedProcessingEndDate`                 date DEFAULT NULL,
        `ConfirmedProcessingEndTime`                 time DEFAULT NULL,
        `ConfirmedWaitDuration`                      float(11) DEFAULT NULL,
        `WaitDurationUnit`                           varchar(3) DEFAULT NULL,
        `ConfirmedQueueDuration`                     float(11) DEFAULT NULL,
        `QueueDurationUnit`                          varchar(3) DEFAULT NULL,
        `ConfirmedMoveDuration`                      float(11) DEFAULT NULL,
        `MoveDurationUnit`                           varchar(3) DEFAULT NULL,
        `ConfirmedYieldQuantity`                     float(15) DEFAULT NULL,
        `ConfirmedScrapQuantity`                     float(15) DEFAULT NULL,
        `OperationVarianceReason`                    varchar(200) DEFAULT NULL,
		`CreationDate`                               date NOT NULL,
		`CreationTime`                               time NOT NULL,
		`LastChangeDate`                             date NOT NULL,
		`LastChangeTime`                             time NOT NULL,
    	`IsCancelled`                                tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`InspectionLot`, `Operations`, `OperationsItem`, `OperationID`, `ConfirmationCountingID`),
	
    CONSTRAINT `DPFMInspectionLotConfHeaderData_fk` FOREIGN KEY (`InspectionLot`, `Operations`, `OperationsItem`, `OperationID`) REFERENCES `data_platform_inspection_lot_operation_data` (`InspectionLot`, `Operations`, `OperationsItem`, `OperationID`),
    -- CONSTRAINT `DPFMInspectionLotConfHeaderDataInspection_fk` FOREIGN KEY (`InspectionLot`, `Inspection`) REFERENCES `data_platform_inspection_lot_inspection_data` (`InspectionLot`, `Inspection`), テーブルなし
    CONSTRAINT `DPFMInspectionLotConfHeaderDataProductionOrder_fk` FOREIGN KEY (`ProductionOrder`, `ProductionOrderItem`) REFERENCES `data_platform_production_order_item_data` (`ProductionOrder`, `ProductionOrderItem`),
    CONSTRAINT `DPFMInspectionLotConfHeaderDataProductBaseUnit_fk` FOREIGN KEY (`ProductBaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMInspectionLotConfHeaderDataProductProductionUnit_fk` FOREIGN KEY (`ProductProductionUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMInspectionLotConfHeaderDataProductOperationUnit_fk` FOREIGN KEY (`ProductOperationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMInspectionLotConfHeaderDataWorkCenter_fk` FOREIGN KEY (`WorkCenter`) REFERENCES `data_platform_work_center_general_data` (`WorkCenter`),
    CONSTRAINT `DPFMInspectionLotConfHeaderDataWaitDurationUnit_fk` FOREIGN KEY (`WaitDurationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMInspectionLotConfHeaderDataQueueDurationUnit_fk` FOREIGN KEY (`QueueDurationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMInspectionLotConfHeaderDataMoveDurationUnit_fk` FOREIGN KEY (`MoveDurationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
